/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "spi_master.v:1" *)
module \$paramod\spi_master\mode=0 (clk, en, rst, tx_en, rx_en, miso, address, data_out, sclk, cs_active, mosi, data_in, rx_valid);
  (* src = "spi_master.v:36" *)
  wire [7:0] _0000_;
  (* src = "spi_master.v:36" *)
  wire [7:0] _0001_;
  (* src = "spi_master.v:36" *)
  wire _0002_;
  (* src = "spi_master.v:36" *)
  wire [7:0] _0003_;
  (* src = "spi_master.v:36" *)
  wire _0004_;
  (* src = "spi_master.v:36" *)
  wire _0005_;
  (* src = "spi_master.v:36" *)
  wire [7:0] _0006_;
  (* src = "spi_master.v:36" *)
  wire _0007_;
  (* src = "spi_master.v:36" *)
  wire _0008_;
  (* src = "spi_master.v:36" *)
  wire _0009_;
  (* src = "spi_master.v:36" *)
  wire [15:0] _0010_;
  (* src = "spi_master.v:36" *)
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  (* src = "spi_master.v:34" *)
  wire CPHA;
  (* src = "spi_master.v:33" *)
  wire CPOL;
  (* src = "spi_master.v:11" *)
  input [7:0] address;
  (* src = "spi_master.v:21" *)
  reg [7:0] bit_count;
  (* src = "spi_master.v:5" *)
  input clk;
  (* src = "spi_master.v:20" *)
  reg [7:0] count;
  (* init = 1'h0 *)
  (* src = "spi_master.v:14" *)
  output cs_active;
  reg cs_active = 1'h0;
  (* init = 8'h00 *)
  (* src = "spi_master.v:16" *)
  output [7:0] data_in;
  reg [7:0] data_in = 8'h00;
  (* src = "spi_master.v:12" *)
  input [7:0] data_out;
  (* src = "spi_master.v:6" *)
  input en;
  (* src = "spi_master.v:31" *)
  reg is_write;
  (* src = "spi_master.v:10" *)
  input miso;
  (* init = 1'h0 *)
  (* src = "spi_master.v:15" *)
  output mosi;
  reg mosi = 1'h0;
  (* src = "spi_master.v:7" *)
  input rst;
  (* src = "spi_master.v:23" *)
  reg [7:0] rx_data;
  (* src = "spi_master.v:9" *)
  input rx_en;
  (* src = "spi_master.v:29" *)
  reg rx_en_reg;
  (* init = 1'h0 *)
  (* src = "spi_master.v:17" *)
  output rx_valid;
  reg rx_valid = 1'h0;
  (* init = 1'h0 *)
  (* src = "spi_master.v:13" *)
  output sclk;
  reg sclk = 1'h0;
  (* src = "spi_master.v:22" *)
  reg [15:0] tx_data;
  (* src = "spi_master.v:8" *)
  input tx_en;
  (* src = "spi_master.v:28" *)
  reg tx_en_reg;
  assign _0011_ = tx_en & ~(rst);
  assign _0007_ = rx_en & ~(rst);
  assign _0012_ = ~rst;
  assign _0013_ = ~rx_data[0];
  assign _0014_ = ~en;
  assign _0015_ = ~cs_active;
  assign _0016_ = rx_en_reg & ~(rx_en);
  assign _0017_ = _0016_ | _0013_;
  assign _0018_ = tx_en_reg & ~(tx_en);
  assign _0019_ = _0018_ | _0017_;
  assign _0020_ = ~miso;
  assign _0021_ = bit_count[7] | bit_count[6];
  assign _0022_ = bit_count[5] | bit_count[4];
  assign _0023_ = _0022_ | _0021_;
  assign _0024_ = bit_count[2] | ~(bit_count[3]);
  assign _0025_ = bit_count[1] | ~(bit_count[0]);
  assign _0026_ = _0025_ | _0024_;
  assign _0027_ = _0026_ | _0023_;
  assign _0028_ = ~(_0022_ | _0021_);
  assign _0029_ = ~bit_count[1];
  assign _0030_ = ~bit_count[2];
  assign _0031_ = ~bit_count[3];
  assign _0032_ = ~((_0030_ & _0029_) | _0031_);
  assign _0033_ = _0028_ & ~(_0032_);
  assign _0034_ = ~((_0033_ & _0027_) | is_write);
  assign _0035_ = bit_count[5] | ~(bit_count[4]);
  assign _0036_ = _0035_ | _0021_;
  assign _0037_ = bit_count[3] | bit_count[2];
  assign _0038_ = _0037_ | bit_count[1];
  assign _0039_ = ~((_0038_ | _0036_) & _0023_);
  assign _0040_ = _0037_ | _0025_;
  assign _0041_ = ~((_0040_ | _0036_) & _0039_);
  assign _0042_ = _0034_ & ~(_0041_);
  assign _0043_ = _0042_ ? _0020_ : _0013_;
  assign _0044_ = sclk ? _0013_ : _0043_;
  assign _0045_ = count[1] | ~(count[0]);
  assign _0046_ = count[3] | count[2];
  assign _0047_ = _0046_ | _0045_;
  assign _0048_ = count[5] | count[4];
  assign _0049_ = count[7] | count[6];
  assign _0050_ = _0049_ | _0048_;
  assign _0051_ = _0050_ | _0047_;
  assign _0052_ = _0051_ ? _0013_ : _0044_;
  assign _0053_ = cs_active ? _0052_ : _0019_;
  assign _0054_ = en ? _0053_ : _0013_;
  assign _0006_[0] = _0012_ & ~(_0054_);
  assign _0055_ = ~rx_data[1];
  assign _0056_ = _0016_ | _0055_;
  assign _0057_ = _0056_ | _0018_;
  assign _0058_ = _0042_ ? _0013_ : _0055_;
  assign _0059_ = sclk ? _0055_ : _0058_;
  assign _0060_ = _0051_ ? _0055_ : _0059_;
  assign _0061_ = cs_active ? _0060_ : _0057_;
  assign _0062_ = en ? _0061_ : _0055_;
  assign _0006_[1] = _0012_ & ~(_0062_);
  assign _0063_ = ~rx_data[2];
  assign _0064_ = _0016_ | _0063_;
  assign _0065_ = _0064_ | _0018_;
  assign _0066_ = _0042_ ? _0055_ : _0063_;
  assign _0067_ = sclk ? _0063_ : _0066_;
  assign _0068_ = _0051_ ? _0063_ : _0067_;
  assign _0069_ = cs_active ? _0068_ : _0065_;
  assign _0070_ = en ? _0069_ : _0063_;
  assign _0006_[2] = _0012_ & ~(_0070_);
  assign _0071_ = ~rx_data[3];
  assign _0072_ = _0016_ | _0071_;
  assign _0073_ = _0072_ | _0018_;
  assign _0074_ = _0042_ ? _0063_ : _0071_;
  assign _0075_ = sclk ? _0071_ : _0074_;
  assign _0076_ = _0051_ ? _0071_ : _0075_;
  assign _0077_ = cs_active ? _0076_ : _0073_;
  assign _0078_ = en ? _0077_ : _0071_;
  assign _0006_[3] = _0012_ & ~(_0078_);
  assign _0079_ = ~rx_data[4];
  assign _0080_ = _0016_ | _0079_;
  assign _0081_ = _0080_ | _0018_;
  assign _0082_ = _0042_ ? _0071_ : _0079_;
  assign _0083_ = sclk ? _0079_ : _0082_;
  assign _0084_ = _0051_ ? _0079_ : _0083_;
  assign _0085_ = cs_active ? _0084_ : _0081_;
  assign _0086_ = en ? _0085_ : _0079_;
  assign _0006_[4] = _0012_ & ~(_0086_);
  assign _0087_ = ~rx_data[5];
  assign _0088_ = _0016_ | _0087_;
  assign _0089_ = _0088_ | _0018_;
  assign _0090_ = _0042_ ? _0079_ : _0087_;
  assign _0091_ = sclk ? _0087_ : _0090_;
  assign _0092_ = _0051_ ? _0087_ : _0091_;
  assign _0093_ = cs_active ? _0092_ : _0089_;
  assign _0094_ = en ? _0093_ : _0087_;
  assign _0006_[5] = _0012_ & ~(_0094_);
  assign _0095_ = ~rx_data[6];
  assign _0096_ = _0016_ | _0095_;
  assign _0097_ = _0096_ | _0018_;
  assign _0098_ = _0042_ ? _0087_ : _0095_;
  assign _0099_ = sclk ? _0095_ : _0098_;
  assign _0100_ = _0051_ ? _0095_ : _0099_;
  assign _0101_ = cs_active ? _0100_ : _0097_;
  assign _0102_ = en ? _0101_ : _0095_;
  assign _0006_[6] = _0012_ & ~(_0102_);
  assign _0103_ = ~rx_data[7];
  assign _0104_ = _0016_ | _0103_;
  assign _0105_ = _0104_ | _0018_;
  assign _0106_ = _0042_ ? _0095_ : _0103_;
  assign _0107_ = sclk ? _0103_ : _0106_;
  assign _0108_ = _0051_ ? _0103_ : _0107_;
  assign _0109_ = cs_active ? _0108_ : _0105_;
  assign _0110_ = en ? _0109_ : _0103_;
  assign _0006_[7] = _0012_ & ~(_0110_);
  assign _0111_ = ~is_write;
  assign _0112_ = ~_0016_;
  assign _0113_ = ~((_0112_ & is_write) | _0018_);
  assign _0114_ = cs_active ? _0111_ : _0113_;
  assign _0115_ = en ? _0114_ : _0111_;
  assign _0004_ = _0012_ & ~(_0115_);
  assign _0116_ = ~count[0];
  assign _0117_ = _0016_ | _0116_;
  assign _0118_ = _0117_ | _0018_;
  assign _0119_ = ~(_0051_ & _0116_);
  assign _0120_ = cs_active ? _0119_ : _0118_;
  assign _0121_ = en ? _0120_ : _0116_;
  assign _0001_[0] = _0012_ & ~(_0121_);
  assign _0122_ = ~count[1];
  assign _0123_ = _0016_ | _0122_;
  assign _0124_ = _0123_ | _0018_;
  assign _0125_ = count[0] ^ count[1];
  assign _0126_ = ~(_0125_ & _0051_);
  assign _0127_ = cs_active ? _0126_ : _0124_;
  assign _0128_ = en ? _0127_ : _0122_;
  assign _0001_[1] = _0012_ & ~(_0128_);
  assign _0129_ = ~count[2];
  assign _0130_ = _0016_ | _0129_;
  assign _0131_ = _0130_ | _0018_;
  assign _0132_ = count[0] & count[1];
  assign _0133_ = _0132_ ^ count[2];
  assign _0134_ = ~(_0133_ & _0051_);
  assign _0135_ = cs_active ? _0134_ : _0131_;
  assign _0136_ = en ? _0135_ : _0129_;
  assign _0001_[2] = _0012_ & ~(_0136_);
  assign _0137_ = ~count[3];
  assign _0138_ = _0016_ | _0137_;
  assign _0139_ = _0138_ | _0018_;
  assign _0140_ = _0132_ & ~(_0129_);
  assign _0141_ = _0140_ ^ _0137_;
  assign _0142_ = _0141_ | ~(_0051_);
  assign _0143_ = cs_active ? _0142_ : _0139_;
  assign _0144_ = en ? _0143_ : _0137_;
  assign _0001_[3] = _0012_ & ~(_0144_);
  assign _0145_ = ~count[4];
  assign _0146_ = _0016_ | _0145_;
  assign _0147_ = _0146_ | _0018_;
  assign _0148_ = ~(count[3] & count[2]);
  assign _0149_ = _0132_ & ~(_0148_);
  assign _0150_ = _0149_ ^ _0145_;
  assign _0151_ = _0150_ | ~(_0051_);
  assign _0152_ = cs_active ? _0151_ : _0147_;
  assign _0153_ = en ? _0152_ : _0145_;
  assign _0001_[4] = _0012_ & ~(_0153_);
  assign _0154_ = ~count[5];
  assign _0155_ = _0016_ | _0154_;
  assign _0156_ = _0155_ | _0018_;
  assign _0157_ = _0149_ & ~(_0145_);
  assign _0158_ = _0157_ ^ _0154_;
  assign _0159_ = _0158_ | ~(_0051_);
  assign _0160_ = cs_active ? _0159_ : _0156_;
  assign _0161_ = en ? _0160_ : _0154_;
  assign _0001_[5] = _0012_ & ~(_0161_);
  assign _0162_ = ~count[6];
  assign _0163_ = _0016_ | _0162_;
  assign _0164_ = _0163_ | _0018_;
  assign _0165_ = count[5] & count[4];
  assign _0166_ = ~(_0165_ & _0149_);
  assign _0167_ = _0166_ ^ count[6];
  assign _0168_ = _0167_ | ~(_0051_);
  assign _0169_ = cs_active ? _0168_ : _0164_;
  assign _0170_ = en ? _0169_ : _0162_;
  assign _0001_[6] = _0012_ & ~(_0170_);
  assign _0171_ = ~count[7];
  assign _0172_ = _0016_ | _0171_;
  assign _0173_ = _0172_ | _0018_;
  assign _0174_ = count[6] & ~(_0166_);
  assign _0175_ = _0174_ ^ _0171_;
  assign _0176_ = _0175_ | ~(_0051_);
  assign _0177_ = cs_active ? _0176_ : _0173_;
  assign _0178_ = en ? _0177_ : _0171_;
  assign _0001_[7] = _0012_ & ~(_0178_);
  assign _0179_ = ~tx_data[0];
  assign _0180_ = ~data_out[0];
  assign _0181_ = _0016_ | _0179_;
  assign _0182_ = _0018_ ? _0180_ : _0181_;
  assign _0183_ = ~sclk;
  assign _0184_ = bit_count[1] | bit_count[0];
  assign _0185_ = _0184_ | _0024_;
  assign _0186_ = ~((_0185_ & bit_count[3]) | _0023_);
  assign _0187_ = _0185_ | _0023_;
  assign _0188_ = ~((_0187_ & _0186_) | is_write);
  assign _0189_ = ~((_0188_ | _0041_) & tx_data[0]);
  assign _0190_ = sclk ? _0189_ : _0179_;
  assign _0191_ = _0051_ ? _0179_ : _0190_;
  assign _0192_ = cs_active ? _0191_ : _0182_;
  assign _0193_ = en ? _0192_ : _0179_;
  assign _0010_[0] = _0012_ & ~(_0193_);
  assign _0194_ = ~tx_data[1];
  assign _0195_ = ~data_out[1];
  assign _0196_ = _0016_ | _0194_;
  assign _0197_ = _0018_ ? _0195_ : _0196_;
  assign _0198_ = ~(_0184_ | _0024_);
  assign _0199_ = ~((_0198_ | _0031_) & _0028_);
  assign _0200_ = _0028_ & ~(_0185_);
  assign _0201_ = ~((_0200_ | _0199_) & _0111_);
  assign _0202_ = _0201_ ? _0179_ : _0194_;
  assign _0203_ = _0041_ ? _0194_ : _0202_;
  assign _0204_ = sclk ? _0203_ : _0194_;
  assign _0205_ = _0051_ ? _0194_ : _0204_;
  assign _0206_ = cs_active ? _0205_ : _0197_;
  assign _0207_ = en ? _0206_ : _0194_;
  assign _0010_[1] = _0012_ & ~(_0207_);
  assign _0208_ = ~tx_data[2];
  assign _0209_ = ~data_out[2];
  assign _0210_ = _0016_ | _0208_;
  assign _0211_ = _0018_ ? _0209_ : _0210_;
  assign _0212_ = _0201_ ? _0194_ : _0208_;
  assign _0213_ = _0041_ ? _0208_ : _0212_;
  assign _0214_ = sclk ? _0213_ : _0208_;
  assign _0215_ = _0051_ ? _0208_ : _0214_;
  assign _0216_ = cs_active ? _0215_ : _0211_;
  assign _0217_ = en ? _0216_ : _0208_;
  assign _0010_[2] = _0012_ & ~(_0217_);
  assign _0218_ = ~tx_data[3];
  assign _0219_ = ~data_out[3];
  assign _0220_ = _0016_ | _0218_;
  assign _0221_ = _0018_ ? _0219_ : _0220_;
  assign _0222_ = _0201_ ? _0208_ : _0218_;
  assign _0223_ = _0041_ ? _0218_ : _0222_;
  assign _0224_ = sclk ? _0223_ : _0218_;
  assign _0225_ = _0051_ ? _0218_ : _0224_;
  assign _0226_ = cs_active ? _0225_ : _0221_;
  assign _0227_ = en ? _0226_ : _0218_;
  assign _0010_[3] = _0012_ & ~(_0227_);
  assign _0228_ = ~tx_data[4];
  assign _0229_ = ~data_out[4];
  assign _0230_ = _0016_ | _0228_;
  assign _0231_ = _0018_ ? _0229_ : _0230_;
  assign _0232_ = _0201_ ? _0218_ : _0228_;
  assign _0233_ = _0041_ ? _0228_ : _0232_;
  assign _0234_ = sclk ? _0233_ : _0228_;
  assign _0235_ = _0051_ ? _0228_ : _0234_;
  assign _0236_ = cs_active ? _0235_ : _0231_;
  assign _0237_ = en ? _0236_ : _0228_;
  assign _0010_[4] = _0012_ & ~(_0237_);
  assign _0238_ = ~tx_data[5];
  assign _0239_ = ~data_out[5];
  assign _0240_ = _0016_ | _0238_;
  assign _0241_ = _0018_ ? _0239_ : _0240_;
  assign _0242_ = _0201_ ? _0228_ : _0238_;
  assign _0243_ = _0041_ ? _0238_ : _0242_;
  assign _0244_ = sclk ? _0243_ : _0238_;
  assign _0245_ = _0051_ ? _0238_ : _0244_;
  assign _0246_ = cs_active ? _0245_ : _0241_;
  assign _0247_ = en ? _0246_ : _0238_;
  assign _0010_[5] = _0012_ & ~(_0247_);
  assign _0248_ = ~tx_data[6];
  assign _0249_ = ~data_out[6];
  assign _0250_ = _0016_ | _0248_;
  assign _0251_ = _0018_ ? _0249_ : _0250_;
  assign _0252_ = _0201_ ? _0238_ : _0248_;
  assign _0253_ = _0041_ ? _0248_ : _0252_;
  assign _0254_ = sclk ? _0253_ : _0248_;
  assign _0255_ = _0051_ ? _0248_ : _0254_;
  assign _0256_ = cs_active ? _0255_ : _0251_;
  assign _0257_ = en ? _0256_ : _0248_;
  assign _0010_[6] = _0012_ & ~(_0257_);
  assign _0258_ = ~tx_data[7];
  assign _0259_ = ~data_out[7];
  assign _0260_ = _0016_ | _0258_;
  assign _0261_ = _0018_ ? _0259_ : _0260_;
  assign _0262_ = _0201_ ? _0248_ : _0258_;
  assign _0263_ = _0041_ ? _0258_ : _0262_;
  assign _0264_ = sclk ? _0263_ : _0258_;
  assign _0265_ = _0051_ ? _0258_ : _0264_;
  assign _0266_ = cs_active ? _0265_ : _0261_;
  assign _0267_ = en ? _0266_ : _0258_;
  assign _0010_[7] = _0012_ & ~(_0267_);
  assign _0268_ = ~tx_data[8];
  assign _0269_ = ~address[0];
  assign _0270_ = _0016_ ? _0269_ : _0268_;
  assign _0271_ = _0018_ ? _0269_ : _0270_;
  assign _0272_ = _0201_ ? _0258_ : _0268_;
  assign _0273_ = _0041_ ? _0268_ : _0272_;
  assign _0274_ = sclk ? _0273_ : _0268_;
  assign _0275_ = _0051_ ? _0268_ : _0274_;
  assign _0276_ = cs_active ? _0275_ : _0271_;
  assign _0277_ = en ? _0276_ : _0268_;
  assign _0010_[8] = _0012_ & ~(_0277_);
  assign _0278_ = ~tx_data[9];
  assign _0279_ = ~address[1];
  assign _0280_ = _0016_ ? _0279_ : _0278_;
  assign _0281_ = _0018_ ? _0279_ : _0280_;
  assign _0282_ = _0201_ ? _0268_ : _0278_;
  assign _0283_ = _0041_ ? _0278_ : _0282_;
  assign _0284_ = sclk ? _0283_ : _0278_;
  assign _0285_ = _0051_ ? _0278_ : _0284_;
  assign _0286_ = cs_active ? _0285_ : _0281_;
  assign _0287_ = en ? _0286_ : _0278_;
  assign _0010_[9] = _0012_ & ~(_0287_);
  assign _0288_ = ~tx_data[10];
  assign _0289_ = ~address[2];
  assign _0290_ = _0016_ ? _0289_ : _0288_;
  assign _0291_ = _0018_ ? _0289_ : _0290_;
  assign _0292_ = _0201_ ? _0278_ : _0288_;
  assign _0293_ = _0041_ ? _0288_ : _0292_;
  assign _0294_ = sclk ? _0293_ : _0288_;
  assign _0295_ = _0051_ ? _0288_ : _0294_;
  assign _0296_ = cs_active ? _0295_ : _0291_;
  assign _0297_ = en ? _0296_ : _0288_;
  assign _0010_[10] = _0012_ & ~(_0297_);
  assign _0298_ = ~tx_data[11];
  assign _0299_ = ~address[3];
  assign _0300_ = _0016_ ? _0299_ : _0298_;
  assign _0301_ = _0018_ ? _0299_ : _0300_;
  assign _0302_ = _0201_ ? _0288_ : _0298_;
  assign _0303_ = _0041_ ? _0298_ : _0302_;
  assign _0304_ = sclk ? _0303_ : _0298_;
  assign _0305_ = _0051_ ? _0298_ : _0304_;
  assign _0306_ = cs_active ? _0305_ : _0301_;
  assign _0307_ = en ? _0306_ : _0298_;
  assign _0010_[11] = _0012_ & ~(_0307_);
  assign _0308_ = ~tx_data[12];
  assign _0309_ = ~address[4];
  assign _0310_ = _0016_ ? _0309_ : _0308_;
  assign _0311_ = _0018_ ? _0309_ : _0310_;
  assign _0312_ = _0201_ ? _0298_ : _0308_;
  assign _0313_ = _0041_ ? _0308_ : _0312_;
  assign _0314_ = sclk ? _0313_ : _0308_;
  assign _0315_ = _0051_ ? _0308_ : _0314_;
  assign _0316_ = cs_active ? _0315_ : _0311_;
  assign _0317_ = en ? _0316_ : _0308_;
  assign _0010_[12] = _0012_ & ~(_0317_);
  assign _0318_ = ~tx_data[13];
  assign _0319_ = ~address[5];
  assign _0320_ = _0016_ ? _0319_ : _0318_;
  assign _0321_ = _0018_ ? _0319_ : _0320_;
  assign _0322_ = _0201_ ? _0308_ : _0318_;
  assign _0323_ = _0041_ ? _0318_ : _0322_;
  assign _0324_ = sclk ? _0323_ : _0318_;
  assign _0325_ = _0051_ ? _0318_ : _0324_;
  assign _0326_ = cs_active ? _0325_ : _0321_;
  assign _0327_ = en ? _0326_ : _0318_;
  assign _0010_[13] = _0012_ & ~(_0327_);
  assign _0328_ = ~tx_data[14];
  assign _0329_ = ~address[6];
  assign _0330_ = _0016_ ? _0329_ : _0328_;
  assign _0331_ = _0018_ ? _0329_ : _0330_;
  assign _0332_ = _0201_ ? _0318_ : _0328_;
  assign _0333_ = _0041_ ? _0328_ : _0332_;
  assign _0334_ = sclk ? _0333_ : _0328_;
  assign _0335_ = _0051_ ? _0328_ : _0334_;
  assign _0336_ = cs_active ? _0335_ : _0331_;
  assign _0337_ = en ? _0336_ : _0328_;
  assign _0010_[14] = _0012_ & ~(_0337_);
  assign _0338_ = ~tx_data[15];
  assign _0339_ = ~address[7];
  assign _0340_ = _0016_ ? _0339_ : _0338_;
  assign _0341_ = _0018_ ? _0339_ : _0340_;
  assign _0342_ = _0201_ ? _0328_ : _0338_;
  assign _0343_ = _0041_ ? _0338_ : _0342_;
  assign _0344_ = sclk ? _0343_ : _0338_;
  assign _0345_ = _0051_ ? _0338_ : _0344_;
  assign _0346_ = cs_active ? _0345_ : _0341_;
  assign _0347_ = en ? _0346_ : _0338_;
  assign _0010_[15] = _0012_ & ~(_0347_);
  assign _0348_ = ~bit_count[0];
  assign _0349_ = _0016_ | _0348_;
  assign _0350_ = _0349_ | _0018_;
  assign _0351_ = bit_count[0] ^ sclk;
  assign _0352_ = _0051_ ? _0348_ : _0351_;
  assign _0353_ = cs_active ? _0352_ : _0350_;
  assign _0354_ = en ? _0353_ : _0348_;
  assign _0000_[0] = _0012_ & ~(_0354_);
  assign _0355_ = _0016_ | _0029_;
  assign _0356_ = _0355_ | _0018_;
  assign _0357_ = ~(bit_count[1] ^ bit_count[0]);
  assign _0358_ = sclk ? _0029_ : _0357_;
  assign _0359_ = _0051_ ? _0029_ : _0358_;
  assign _0360_ = cs_active ? _0359_ : _0356_;
  assign _0361_ = en ? _0360_ : _0029_;
  assign _0000_[1] = _0012_ & ~(_0361_);
  assign _0362_ = _0016_ | _0030_;
  assign _0363_ = _0362_ | _0018_;
  assign _0364_ = ~(bit_count[1] & bit_count[0]);
  assign _0365_ = _0364_ ^ bit_count[2];
  assign _0366_ = sclk ? _0030_ : _0365_;
  assign _0367_ = _0051_ ? _0030_ : _0366_;
  assign _0368_ = cs_active ? _0367_ : _0363_;
  assign _0369_ = en ? _0368_ : _0030_;
  assign _0000_[2] = _0012_ & ~(_0369_);
  assign _0370_ = _0016_ | _0031_;
  assign _0371_ = _0370_ | _0018_;
  assign _0372_ = bit_count[2] & ~(_0364_);
  assign _0373_ = _0372_ ^ _0031_;
  assign _0374_ = sclk ? _0031_ : _0373_;
  assign _0375_ = _0051_ ? _0031_ : _0374_;
  assign _0376_ = cs_active ? _0375_ : _0371_;
  assign _0377_ = en ? _0376_ : _0031_;
  assign _0000_[3] = _0012_ & ~(_0377_);
  assign _0378_ = ~bit_count[4];
  assign _0379_ = _0016_ | _0378_;
  assign _0380_ = _0379_ | _0018_;
  assign _0381_ = ~(bit_count[3] & bit_count[2]);
  assign _0382_ = _0381_ | _0364_;
  assign _0383_ = _0382_ ^ bit_count[4];
  assign _0384_ = sclk ? _0378_ : _0383_;
  assign _0385_ = _0051_ ? _0378_ : _0384_;
  assign _0386_ = cs_active ? _0385_ : _0380_;
  assign _0387_ = en ? _0386_ : _0378_;
  assign _0000_[4] = _0012_ & ~(_0387_);
  assign _0388_ = ~bit_count[5];
  assign _0389_ = _0016_ | _0388_;
  assign _0390_ = _0389_ | _0018_;
  assign _0391_ = bit_count[4] & ~(_0382_);
  assign _0392_ = _0391_ ^ _0388_;
  assign _0393_ = sclk ? _0388_ : _0392_;
  assign _0394_ = _0051_ ? _0388_ : _0393_;
  assign _0395_ = cs_active ? _0394_ : _0390_;
  assign _0396_ = en ? _0395_ : _0388_;
  assign _0000_[5] = _0012_ & ~(_0396_);
  assign _0397_ = ~bit_count[6];
  assign _0398_ = _0016_ | _0397_;
  assign _0399_ = _0398_ | _0018_;
  assign _0400_ = ~(bit_count[5] & bit_count[4]);
  assign _0401_ = _0400_ | _0382_;
  assign _0402_ = _0401_ ^ bit_count[6];
  assign _0403_ = sclk ? _0397_ : _0402_;
  assign _0404_ = _0051_ ? _0397_ : _0403_;
  assign _0405_ = cs_active ? _0404_ : _0399_;
  assign _0406_ = en ? _0405_ : _0397_;
  assign _0000_[6] = _0012_ & ~(_0406_);
  assign _0407_ = ~bit_count[7];
  assign _0408_ = _0016_ | _0407_;
  assign _0409_ = _0408_ | _0018_;
  assign _0410_ = bit_count[6] & ~(_0401_);
  assign _0411_ = _0410_ ^ _0407_;
  assign _0412_ = sclk ? _0407_ : _0411_;
  assign _0413_ = _0051_ ? _0407_ : _0412_;
  assign _0414_ = cs_active ? _0413_ : _0409_;
  assign _0415_ = en ? _0414_ : _0407_;
  assign _0000_[7] = _0012_ & ~(_0415_);
  assign _0416_ = ~(_0041_ & _0111_);
  assign _0417_ = _0416_ | _0183_;
  assign _0418_ = _0417_ | _0051_;
  assign _0419_ = _0418_ | _0015_;
  assign _0420_ = _0419_ | _0014_;
  assign _0008_ = _0012_ & ~(_0420_);
  assign _0421_ = ~data_in[0];
  assign _0422_ = is_write ? _0421_ : _0013_;
  assign _0423_ = _0041_ ? _0422_ : _0421_;
  assign _0424_ = sclk ? _0423_ : _0421_;
  assign _0425_ = _0051_ ? _0421_ : _0424_;
  assign _0426_ = cs_active ? _0425_ : _0421_;
  assign _0427_ = en ? _0426_ : _0421_;
  assign _0003_[0] = _0012_ & ~(_0427_);
  assign _0428_ = ~data_in[1];
  assign _0429_ = is_write ? _0428_ : _0055_;
  assign _0430_ = _0041_ ? _0429_ : _0428_;
  assign _0431_ = sclk ? _0430_ : _0428_;
  assign _0432_ = _0051_ ? _0428_ : _0431_;
  assign _0433_ = cs_active ? _0432_ : _0428_;
  assign _0434_ = en ? _0433_ : _0428_;
  assign _0003_[1] = _0012_ & ~(_0434_);
  assign _0435_ = ~data_in[2];
  assign _0436_ = is_write ? _0435_ : _0063_;
  assign _0437_ = _0041_ ? _0436_ : _0435_;
  assign _0438_ = sclk ? _0437_ : _0435_;
  assign _0439_ = _0051_ ? _0435_ : _0438_;
  assign _0440_ = cs_active ? _0439_ : _0435_;
  assign _0441_ = en ? _0440_ : _0435_;
  assign _0003_[2] = _0012_ & ~(_0441_);
  assign _0442_ = ~data_in[3];
  assign _0443_ = is_write ? _0442_ : _0071_;
  assign _0444_ = _0041_ ? _0443_ : _0442_;
  assign _0445_ = sclk ? _0444_ : _0442_;
  assign _0446_ = _0051_ ? _0442_ : _0445_;
  assign _0447_ = cs_active ? _0446_ : _0442_;
  assign _0448_ = en ? _0447_ : _0442_;
  assign _0003_[3] = _0012_ & ~(_0448_);
  assign _0449_ = ~data_in[4];
  assign _0450_ = is_write ? _0449_ : _0079_;
  assign _0451_ = _0041_ ? _0450_ : _0449_;
  assign _0452_ = sclk ? _0451_ : _0449_;
  assign _0453_ = _0051_ ? _0449_ : _0452_;
  assign _0454_ = cs_active ? _0453_ : _0449_;
  assign _0455_ = en ? _0454_ : _0449_;
  assign _0003_[4] = _0012_ & ~(_0455_);
  assign _0456_ = ~data_in[5];
  assign _0457_ = is_write ? _0456_ : _0087_;
  assign _0458_ = _0041_ ? _0457_ : _0456_;
  assign _0459_ = sclk ? _0458_ : _0456_;
  assign _0460_ = _0051_ ? _0456_ : _0459_;
  assign _0461_ = cs_active ? _0460_ : _0456_;
  assign _0462_ = en ? _0461_ : _0456_;
  assign _0003_[5] = _0012_ & ~(_0462_);
  assign _0463_ = ~data_in[6];
  assign _0464_ = is_write ? _0463_ : _0095_;
  assign _0465_ = _0041_ ? _0464_ : _0463_;
  assign _0466_ = sclk ? _0465_ : _0463_;
  assign _0467_ = _0051_ ? _0463_ : _0466_;
  assign _0468_ = cs_active ? _0467_ : _0463_;
  assign _0469_ = en ? _0468_ : _0463_;
  assign _0003_[6] = _0012_ & ~(_0469_);
  assign _0470_ = ~data_in[7];
  assign _0471_ = is_write ? _0470_ : _0103_;
  assign _0472_ = _0041_ ? _0471_ : _0470_;
  assign _0473_ = sclk ? _0472_ : _0470_;
  assign _0474_ = _0051_ ? _0470_ : _0473_;
  assign _0475_ = cs_active ? _0474_ : _0470_;
  assign _0476_ = en ? _0475_ : _0470_;
  assign _0003_[7] = _0012_ & ~(_0476_);
  assign _0477_ = ~((_0112_ & mosi) | _0018_);
  assign _0478_ = ~mosi;
  assign _0479_ = _0188_ | _0338_;
  assign _0480_ = _0479_ | _0041_;
  assign _0481_ = sclk ? _0480_ : _0478_;
  assign _0482_ = _0051_ ? _0478_ : _0481_;
  assign _0483_ = cs_active ? _0482_ : _0477_;
  assign _0484_ = _0483_ | _0014_;
  assign _0005_ = _0012_ & ~(_0484_);
  assign _0485_ = ~(_0018_ | _0016_);
  assign _0486_ = _0015_ & ~(_0485_);
  assign _0487_ = ~_0051_;
  assign _0488_ = _0041_ & ~(_0183_);
  assign _0489_ = ~((_0488_ & _0487_) | _0015_);
  assign _0490_ = ~((_0489_ | _0486_) & en);
  assign _0002_ = _0012_ & ~(_0490_);
  assign _0491_ = _0016_ | _0183_;
  assign _0492_ = _0491_ | _0018_;
  assign _0493_ = _0183_ & ~(_0041_);
  assign _0494_ = sclk & ~(_0493_);
  assign _0495_ = _0051_ ? _0183_ : _0494_;
  assign _0496_ = cs_active ? _0495_ : _0492_;
  assign _0497_ = _0496_ | _0014_;
  assign _0009_ = _0012_ & ~(_0497_);
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      sclk <= _0009_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      cs_active <= _0002_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      mosi <= _0005_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[0] <= _0003_[0];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[1] <= _0003_[1];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[2] <= _0003_[2];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[3] <= _0003_[3];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[4] <= _0003_[4];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[5] <= _0003_[5];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[6] <= _0003_[6];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[7] <= _0003_[7];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_valid <= _0008_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[0] <= _0001_[0];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[1] <= _0001_[1];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[2] <= _0001_[2];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[3] <= _0001_[3];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[4] <= _0001_[4];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[5] <= _0001_[5];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[6] <= _0001_[6];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[7] <= _0001_[7];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[0] <= _0000_[0];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[1] <= _0000_[1];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[2] <= _0000_[2];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[3] <= _0000_[3];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[4] <= _0000_[4];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[5] <= _0000_[5];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[6] <= _0000_[6];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[7] <= _0000_[7];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[0] <= _0010_[0];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[1] <= _0010_[1];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[2] <= _0010_[2];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[3] <= _0010_[3];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[4] <= _0010_[4];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[5] <= _0010_[5];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[6] <= _0010_[6];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[7] <= _0010_[7];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[8] <= _0010_[8];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[9] <= _0010_[9];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[10] <= _0010_[10];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[11] <= _0010_[11];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[12] <= _0010_[12];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[13] <= _0010_[13];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[14] <= _0010_[14];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[15] <= _0010_[15];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[0] <= _0006_[0];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[1] <= _0006_[1];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[2] <= _0006_[2];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[3] <= _0006_[3];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[4] <= _0006_[4];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[5] <= _0006_[5];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[6] <= _0006_[6];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[7] <= _0006_[7];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_en_reg <= _0011_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_en_reg <= _0007_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      is_write <= _0004_;
  assign CPHA = 1'h0;
  assign CPOL = 1'h0;
endmodule

(* src = "spi_slave.v:1" *)
module \$paramod\spi_slave\mode=0 (rst, cs_n, sclk, mosi, miso, address, data_out);
  (* src = "spi_slave.v:36" *)
  wire [7:0] _000_;
  (* src = "spi_slave.v:36" *)
  (* unused_bits = "7" *)
  wire [7:0] _001_;
  (* src = "spi_slave.v:36" *)
  wire [7:0] _002_;
  (* src = "spi_slave.v:36" *)
  wire [7:0] _003_;
  (* src = "spi_slave.v:36" *)
  wire _004_;
  (* src = "spi_slave.v:36" *)
  wire _005_;
  (* src = "spi_slave.v:36" *)
  (* unused_bits = "7" *)
  wire [7:0] _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  (* init = 8'h00 *)
  (* src = "spi_slave.v:10" *)
  output [7:0] address;
  reg [7:0] address = 8'h00;
  (* src = "spi_slave.v:19" *)
  (* unused_bits = "7" *)
  wire [7:0] address_shift;
  (* src = "spi_slave.v:16" *)
  reg [7:0] bit_count;
  (* src = "spi_slave.v:6" *)
  input cs_n;
  (* init = 8'h00 *)
  (* src = "spi_slave.v:11" *)
  output [7:0] data_out;
  reg [7:0] data_out = 8'h00;
  (* src = "spi_slave.v:9" *)
  output miso;
  (* src = "spi_slave.v:23" *)
  reg miso_reg;
  (* src = "spi_slave.v:8" *)
  input mosi;
  (* src = "spi_slave.v:5" *)
  input rst;
  (* src = "spi_slave.v:17" *)
  reg rw;
  (* src = "spi_slave.v:20" *)
  (* unused_bits = "7" *)
  wire [7:0] rx_data;
  (* src = "spi_slave.v:7" *)
  input sclk;
  (* src = "spi_slave.v:21" *)
  wire [7:0] tx_data;
  assign _039_ = rst | cs_n;
  assign _040_ = bit_count[3] | bit_count[2];
  assign _041_ = bit_count[1] | bit_count[0];
  assign _042_ = _041_ | _040_;
  assign _043_ = bit_count[7] | bit_count[6];
  assign _044_ = bit_count[5] | bit_count[4];
  assign _045_ = _044_ | _043_;
  assign _046_ = ~(_045_ | _042_);
  assign _047_ = ~_045_;
  assign _048_ = ~bit_count[1];
  assign _049_ = ~bit_count[2];
  assign _050_ = ~bit_count[3];
  assign _051_ = ~((_049_ & _048_) | _050_);
  assign _052_ = _051_ | _045_;
  assign _053_ = bit_count[2] | ~(bit_count[3]);
  assign _054_ = bit_count[1] | ~(bit_count[0]);
  assign _055_ = _054_ | _053_;
  assign _056_ = ~(_055_ | _045_);
  assign _057_ = ~(_056_ | _052_);
  assign _058_ = rw & ~(_057_);
  assign _059_ = bit_count[5] | ~(bit_count[4]);
  assign _060_ = _059_ | _043_;
  assign _061_ = ~(_060_ | _042_);
  assign _062_ = ~((_061_ | _047_) & _058_);
  assign _063_ = _061_ ? mosi : data_out[0];
  assign _064_ = _062_ ? data_out[0] : _063_;
  assign _065_ = _040_ | bit_count[1];
  assign _066_ = _065_ | _045_;
  assign _067_ = ~(_054_ | _040_);
  assign _068_ = ~((_067_ & _047_) | _066_);
  assign _069_ = ~(_053_ | _041_);
  assign _070_ = ~((_069_ | _050_) & _047_);
  assign _071_ = ~(_070_ | _068_);
  assign _072_ = _071_ ? data_out[0] : _064_;
  assign _003_[0] = _046_ ? data_out[0] : _072_;
  assign _073_ = _061_ ? rx_data[0] : data_out[1];
  assign _074_ = _062_ ? data_out[1] : _073_;
  assign _075_ = _071_ ? data_out[1] : _074_;
  assign _003_[1] = _046_ ? data_out[1] : _075_;
  assign _076_ = _061_ ? rx_data[1] : data_out[2];
  assign _077_ = _062_ ? data_out[2] : _076_;
  assign _078_ = _071_ ? data_out[2] : _077_;
  assign _003_[2] = _046_ ? data_out[2] : _078_;
  assign _079_ = _061_ ? rx_data[2] : data_out[3];
  assign _080_ = _062_ ? data_out[3] : _079_;
  assign _081_ = _071_ ? data_out[3] : _080_;
  assign _003_[3] = _046_ ? data_out[3] : _081_;
  assign _082_ = _061_ ? rx_data[3] : data_out[4];
  assign _083_ = _062_ ? data_out[4] : _082_;
  assign _084_ = _071_ ? data_out[4] : _083_;
  assign _003_[4] = _046_ ? data_out[4] : _084_;
  assign _085_ = _061_ ? rx_data[4] : data_out[5];
  assign _086_ = _062_ ? data_out[5] : _085_;
  assign _087_ = _071_ ? data_out[5] : _086_;
  assign _003_[5] = _046_ ? data_out[5] : _087_;
  assign _088_ = _061_ ? rx_data[5] : data_out[6];
  assign _089_ = _062_ ? data_out[6] : _088_;
  assign _090_ = _071_ ? data_out[6] : _089_;
  assign _003_[6] = _046_ ? data_out[6] : _090_;
  assign _091_ = _061_ ? rx_data[6] : data_out[7];
  assign _092_ = _062_ ? data_out[7] : _091_;
  assign _093_ = _071_ ? data_out[7] : _092_;
  assign _003_[7] = _046_ ? data_out[7] : _093_;
  assign _094_ = _069_ & ~(_045_);
  assign _095_ = _094_ ? mosi : address[0];
  assign _096_ = _071_ ? _095_ : address[0];
  assign _000_[0] = _046_ ? address[0] : _096_;
  assign _097_ = _094_ ? address_shift[0] : address[1];
  assign _098_ = _071_ ? _097_ : address[1];
  assign _000_[1] = _046_ ? address[1] : _098_;
  assign _099_ = _094_ ? address_shift[1] : address[2];
  assign _100_ = _071_ ? _099_ : address[2];
  assign _000_[2] = _046_ ? address[2] : _100_;
  assign _101_ = _094_ ? address_shift[2] : address[3];
  assign _102_ = _071_ ? _101_ : address[3];
  assign _000_[3] = _046_ ? address[3] : _102_;
  assign _103_ = _094_ ? address_shift[3] : address[4];
  assign _104_ = _071_ ? _103_ : address[4];
  assign _000_[4] = _046_ ? address[4] : _104_;
  assign _105_ = _094_ ? address_shift[4] : address[5];
  assign _106_ = _071_ ? _105_ : address[5];
  assign _000_[5] = _046_ ? address[5] : _106_;
  assign _107_ = _094_ ? address_shift[5] : address[6];
  assign _108_ = _071_ ? _107_ : address[6];
  assign _000_[6] = _046_ ? address[6] : _108_;
  assign _109_ = _094_ ? address_shift[6] : address[7];
  assign _110_ = _071_ ? _109_ : address[7];
  assign _000_[7] = _046_ ? address[7] : _110_;
  assign _111_ = ~rst;
  assign _112_ = ~(address[0] & cs_n);
  assign _007_ = _111_ & ~(_112_);
  assign _113_ = ~(address[1] & cs_n);
  assign _008_ = _111_ & ~(_113_);
  assign _114_ = ~(address[2] & cs_n);
  assign _009_ = _111_ & ~(_114_);
  assign _115_ = ~(address[3] & cs_n);
  assign _010_ = _111_ & ~(_115_);
  assign _116_ = ~(address[4] & cs_n);
  assign _011_ = _111_ & ~(_116_);
  assign _117_ = ~(address[5] & cs_n);
  assign _012_ = _111_ & ~(_117_);
  assign _118_ = ~(address[6] & cs_n);
  assign _013_ = _111_ & ~(_118_);
  assign _119_ = ~(address[7] & cs_n);
  assign _014_ = _111_ & ~(_119_);
  assign _120_ = ~cs_n;
  assign _023_ = ~((address[0] | _120_) & _111_);
  assign _024_ = ~((address[1] | _120_) & _111_);
  assign _025_ = ~((address[2] | _120_) & _111_);
  assign _026_ = ~((address[3] | _120_) & _111_);
  assign _027_ = ~((address[4] | _120_) & _111_);
  assign _028_ = ~((address[5] | _120_) & _111_);
  assign _029_ = ~((address[6] | _120_) & _111_);
  assign _030_ = ~((address[7] | _120_) & _111_);
  assign _121_ = ~(data_out[0] & cs_n);
  assign _015_ = _111_ & ~(_121_);
  assign _122_ = ~(data_out[1] & cs_n);
  assign _016_ = _111_ & ~(_122_);
  assign _123_ = ~(data_out[2] & cs_n);
  assign _017_ = _111_ & ~(_123_);
  assign _124_ = ~(data_out[3] & cs_n);
  assign _018_ = _111_ & ~(_124_);
  assign _125_ = ~(data_out[4] & cs_n);
  assign _019_ = _111_ & ~(_125_);
  assign _126_ = ~(data_out[5] & cs_n);
  assign _020_ = _111_ & ~(_126_);
  assign _127_ = ~(data_out[6] & cs_n);
  assign _021_ = _111_ & ~(_127_);
  assign _128_ = ~(data_out[7] & cs_n);
  assign _022_ = _111_ & ~(_128_);
  assign _031_ = ~((data_out[0] | _120_) & _111_);
  assign _032_ = ~((data_out[1] | _120_) & _111_);
  assign _033_ = ~((data_out[2] | _120_) & _111_);
  assign _034_ = ~((data_out[3] | _120_) & _111_);
  assign _035_ = ~((data_out[4] | _120_) & _111_);
  assign _036_ = ~((data_out[5] | _120_) & _111_);
  assign _037_ = ~((data_out[6] | _120_) & _111_);
  assign _038_ = ~((data_out[7] | _120_) & _111_);
  assign _129_ = _061_ | _045_;
  assign _130_ = ~rw;
  assign _131_ = ~((_056_ | _052_) & _130_);
  assign _132_ = _131_ | _129_;
  assign _002_[0] = ~bit_count[0];
  assign _133_ = bit_count[4] | ~(bit_count[3]);
  assign _134_ = _133_ | _049_;
  assign _135_ = _048_ & ~(_134_);
  assign _136_ = bit_count[1] & ~(_134_);
  assign _137_ = _136_ | _135_;
  assign _138_ = _133_ | bit_count[2];
  assign _139_ = _048_ & ~(_138_);
  assign _140_ = bit_count[1] & ~(_138_);
  assign _141_ = _140_ | _139_;
  assign _142_ = bit_count[0] ? _141_ : _137_;
  assign _143_ = _132_ ? miso_reg : _142_;
  assign _144_ = _062_ ? _143_ : miso_reg;
  assign _145_ = ~miso_reg;
  assign _146_ = ~((_094_ & _130_) | _145_);
  assign _147_ = _071_ ? _146_ : _144_;
  assign _004_ = _046_ ? miso_reg : _147_;
  assign _005_ = _046_ ? mosi : rw;
  assign _148_ = _071_ ? mosi : address_shift[0];
  assign _001_[0] = _046_ ? address_shift[0] : _148_;
  assign _149_ = _071_ ? address_shift[0] : address_shift[1];
  assign _001_[1] = _046_ ? address_shift[1] : _149_;
  assign _150_ = _071_ ? address_shift[1] : address_shift[2];
  assign _001_[2] = _046_ ? address_shift[2] : _150_;
  assign _151_ = _071_ ? address_shift[2] : address_shift[3];
  assign _001_[3] = _046_ ? address_shift[3] : _151_;
  assign _152_ = _071_ ? address_shift[3] : address_shift[4];
  assign _001_[4] = _046_ ? address_shift[4] : _152_;
  assign _153_ = _071_ ? address_shift[4] : address_shift[5];
  assign _001_[5] = _046_ ? address_shift[5] : _153_;
  assign _154_ = _071_ ? address_shift[5] : address_shift[6];
  assign _001_[6] = _046_ ? address_shift[6] : _154_;
  assign _155_ = _062_ ? rx_data[0] : mosi;
  assign _156_ = _071_ ? rx_data[0] : _155_;
  assign _006_[0] = _046_ ? rx_data[0] : _156_;
  assign _157_ = _062_ ? rx_data[1] : rx_data[0];
  assign _158_ = _071_ ? rx_data[1] : _157_;
  assign _006_[1] = _046_ ? rx_data[1] : _158_;
  assign _159_ = _062_ ? rx_data[2] : rx_data[1];
  assign _160_ = _071_ ? rx_data[2] : _159_;
  assign _006_[2] = _046_ ? rx_data[2] : _160_;
  assign _161_ = _062_ ? rx_data[3] : rx_data[2];
  assign _162_ = _071_ ? rx_data[3] : _161_;
  assign _006_[3] = _046_ ? rx_data[3] : _162_;
  assign _163_ = _062_ ? rx_data[4] : rx_data[3];
  assign _164_ = _071_ ? rx_data[4] : _163_;
  assign _006_[4] = _046_ ? rx_data[4] : _164_;
  assign _165_ = _062_ ? rx_data[5] : rx_data[4];
  assign _166_ = _071_ ? rx_data[5] : _165_;
  assign _006_[5] = _046_ ? rx_data[5] : _166_;
  assign _167_ = _062_ ? rx_data[6] : rx_data[5];
  assign _168_ = _071_ ? rx_data[6] : _167_;
  assign _006_[6] = _046_ ? rx_data[6] : _168_;
  assign _002_[1] = bit_count[1] ^ bit_count[0];
  assign _169_ = ~(bit_count[1] & bit_count[0]);
  assign _002_[2] = _169_ ^ _049_;
  assign _170_ = bit_count[2] & ~(_169_);
  assign _002_[3] = _170_ ^ bit_count[3];
  assign _171_ = ~(bit_count[3] & bit_count[2]);
  assign _172_ = _171_ | _169_;
  assign _002_[4] = ~(_172_ ^ bit_count[4]);
  assign _173_ = bit_count[4] & ~(_172_);
  assign _002_[5] = _173_ ^ bit_count[5];
  assign _174_ = ~(bit_count[5] & bit_count[4]);
  assign _175_ = _174_ | _172_;
  assign _002_[6] = ~(_175_ ^ bit_count[6]);
  assign _176_ = bit_count[6] & ~(_175_);
  assign _002_[7] = _176_ ^ bit_count[7];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _007_ or posedge _023_)
    if (_023_)
      address[0] <= 0;
    else if (_007_)
      address[0] <= 1;
    else
      address[0] <= _000_[0];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _008_ or posedge _024_)
    if (_024_)
      address[1] <= 0;
    else if (_008_)
      address[1] <= 1;
    else
      address[1] <= _000_[1];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _009_ or posedge _025_)
    if (_025_)
      address[2] <= 0;
    else if (_009_)
      address[2] <= 1;
    else
      address[2] <= _000_[2];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _010_ or posedge _026_)
    if (_026_)
      address[3] <= 0;
    else if (_010_)
      address[3] <= 1;
    else
      address[3] <= _000_[3];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _011_ or posedge _027_)
    if (_027_)
      address[4] <= 0;
    else if (_011_)
      address[4] <= 1;
    else
      address[4] <= _000_[4];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _012_ or posedge _028_)
    if (_028_)
      address[5] <= 0;
    else if (_012_)
      address[5] <= 1;
    else
      address[5] <= _000_[5];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _013_ or posedge _029_)
    if (_029_)
      address[6] <= 0;
    else if (_013_)
      address[6] <= 1;
    else
      address[6] <= _000_[6];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _014_ or posedge _030_)
    if (_030_)
      address[7] <= 0;
    else if (_014_)
      address[7] <= 1;
    else
      address[7] <= _000_[7];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _015_ or posedge _031_)
    if (_031_)
      data_out[0] <= 0;
    else if (_015_)
      data_out[0] <= 1;
    else
      data_out[0] <= _003_[0];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _016_ or posedge _032_)
    if (_032_)
      data_out[1] <= 0;
    else if (_016_)
      data_out[1] <= 1;
    else
      data_out[1] <= _003_[1];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _017_ or posedge _033_)
    if (_033_)
      data_out[2] <= 0;
    else if (_017_)
      data_out[2] <= 1;
    else
      data_out[2] <= _003_[2];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _018_ or posedge _034_)
    if (_034_)
      data_out[3] <= 0;
    else if (_018_)
      data_out[3] <= 1;
    else
      data_out[3] <= _003_[3];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _019_ or posedge _035_)
    if (_035_)
      data_out[4] <= 0;
    else if (_019_)
      data_out[4] <= 1;
    else
      data_out[4] <= _003_[4];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _020_ or posedge _036_)
    if (_036_)
      data_out[5] <= 0;
    else if (_020_)
      data_out[5] <= 1;
    else
      data_out[5] <= _003_[5];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _021_ or posedge _037_)
    if (_037_)
      data_out[6] <= 0;
    else if (_021_)
      data_out[6] <= 1;
    else
      data_out[6] <= _003_[6];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _022_ or posedge _038_)
    if (_038_)
      data_out[7] <= 0;
    else if (_022_)
      data_out[7] <= 1;
    else
      data_out[7] <= _003_[7];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[0] <= 0;
    else
      bit_count[0] <= _002_[0];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[1] <= 0;
    else
      bit_count[1] <= _002_[1];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[2] <= 0;
    else
      bit_count[2] <= _002_[2];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[3] <= 0;
    else
      bit_count[3] <= _002_[3];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[4] <= 0;
    else
      bit_count[4] <= _002_[4];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[5] <= 0;
    else
      bit_count[5] <= _002_[5];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[6] <= 0;
    else
      bit_count[6] <= _002_[6];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[7] <= 0;
    else
      bit_count[7] <= _002_[7];
  reg \rx_data_reg[0] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[0]  <= 0;
    else
      \rx_data_reg[0]  <= _006_[0];
  assign rx_data[0] = \rx_data_reg[0] ;
  reg \rx_data_reg[1] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[1]  <= 0;
    else
      \rx_data_reg[1]  <= _006_[1];
  assign rx_data[1] = \rx_data_reg[1] ;
  reg \rx_data_reg[2] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[2]  <= 0;
    else
      \rx_data_reg[2]  <= _006_[2];
  assign rx_data[2] = \rx_data_reg[2] ;
  reg \rx_data_reg[3] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[3]  <= 0;
    else
      \rx_data_reg[3]  <= _006_[3];
  assign rx_data[3] = \rx_data_reg[3] ;
  reg \rx_data_reg[4] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[4]  <= 0;
    else
      \rx_data_reg[4]  <= _006_[4];
  assign rx_data[4] = \rx_data_reg[4] ;
  reg \rx_data_reg[5] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[5]  <= 0;
    else
      \rx_data_reg[5]  <= _006_[5];
  assign rx_data[5] = \rx_data_reg[5] ;
  reg \rx_data_reg[6] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[6]  <= 0;
    else
      \rx_data_reg[6]  <= _006_[6];
  assign rx_data[6] = \rx_data_reg[6] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      rw <= 0;
    else
      rw <= _005_;
  reg \address_shift_reg[0] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[0]  <= 0;
    else
      \address_shift_reg[0]  <= _001_[0];
  assign address_shift[0] = \address_shift_reg[0] ;
  reg \address_shift_reg[1] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[1]  <= 0;
    else
      \address_shift_reg[1]  <= _001_[1];
  assign address_shift[1] = \address_shift_reg[1] ;
  reg \address_shift_reg[2] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[2]  <= 0;
    else
      \address_shift_reg[2]  <= _001_[2];
  assign address_shift[2] = \address_shift_reg[2] ;
  reg \address_shift_reg[3] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[3]  <= 0;
    else
      \address_shift_reg[3]  <= _001_[3];
  assign address_shift[3] = \address_shift_reg[3] ;
  reg \address_shift_reg[4] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[4]  <= 0;
    else
      \address_shift_reg[4]  <= _001_[4];
  assign address_shift[4] = \address_shift_reg[4] ;
  reg \address_shift_reg[5] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[5]  <= 0;
    else
      \address_shift_reg[5]  <= _001_[5];
  assign address_shift[5] = \address_shift_reg[5] ;
  reg \address_shift_reg[6] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[6]  <= 0;
    else
      \address_shift_reg[6]  <= _001_[6];
  assign address_shift[6] = \address_shift_reg[6] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      miso_reg <= 0;
    else
      miso_reg <= _004_;
  assign miso = miso_reg;
  assign tx_data = 8'h5a;
endmodule

(* top =  1  *)
(* src = "spi_system.v:1" *)
module spi_system(clk, rst, en, tx_en, rx_en, slave_sel, address, data_out, data_in, rx_valid);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "spi_system.v:12" *)
  input [7:0] address;
  (* src = "spi_system.v:4" *)
  input clk;
  (* src = "spi_system.v:24" *)
  wire cs_active;
  (* src = "spi_system.v:26" *)
  wire [3:0] cs_n;
  (* src = "spi_system.v:15" *)
  output [7:0] data_in;
  (* src = "spi_system.v:13" *)
  input [7:0] data_out;
  (* src = "spi_system.v:6" *)
  input en;
  (* src = "spi_system.v:22" *)
  wire miso;
  (* src = "spi_system.v:28" *)
  wire miso0;
  (* src = "spi_system.v:29" *)
  wire miso1;
  (* src = "spi_system.v:30" *)
  wire miso2;
  (* src = "spi_system.v:31" *)
  wire miso3;
  (* src = "spi_system.v:21" *)
  wire mosi;
  (* src = "spi_system.v:5" *)
  input rst;
  (* src = "spi_system.v:8" *)
  input rx_en;
  (* src = "spi_system.v:16" *)
  output rx_valid;
  (* src = "spi_system.v:20" *)
  wire sclk;
  (* src = "spi_system.v:10" *)
  input [1:0] slave_sel;
  (* src = "spi_system.v:7" *)
  input tx_en;
  assign _00_ = ~cs_active;
  assign _01_ = slave_sel[0] | ~(slave_sel[1]);
  assign cs_n[2] = _01_ | _00_;
  assign _02_ = cs_n[2] ? miso3 : miso2;
  assign _03_ = slave_sel[1] | ~(slave_sel[0]);
  assign cs_n[1] = _03_ | _00_;
  assign _04_ = cs_n[1] ? _02_ : miso1;
  assign _05_ = slave_sel[0] | slave_sel[1];
  assign cs_n[0] = _05_ | _00_;
  assign miso = cs_n[0] ? _04_ : miso0;
  assign _06_ = ~(slave_sel[0] & slave_sel[1]);
  assign cs_n[3] = _06_ | _00_;
  (* src = "spi_system.v:38" *)
  \$paramod\spi_master\mode=0  master (
    .address(address),
    .clk(clk),
    .cs_active(cs_active),
    .data_in(data_in),
    .data_out(data_out),
    .en(en),
    .miso(miso),
    .mosi(mosi),
    .rst(rst),
    .rx_en(rx_en),
    .rx_valid(rx_valid),
    .sclk(sclk),
    .tx_en(tx_en)
  );
  (* src = "spi_system.v:62" *)
  \$paramod\spi_slave\mode=0  slave0 (
    .cs_n(cs_n[0]),
    .miso(miso0),
    .mosi(mosi),
    .rst(rst),
    .sclk(sclk)
  );
  (* src = "spi_system.v:75" *)
  \$paramod\spi_slave\mode=0  slave1 (
    .cs_n(cs_n[1]),
    .miso(miso1),
    .mosi(mosi),
    .rst(rst),
    .sclk(sclk)
  );
  (* src = "spi_system.v:88" *)
  \$paramod\spi_slave\mode=0  slave2 (
    .cs_n(cs_n[2]),
    .miso(miso2),
    .mosi(mosi),
    .rst(rst),
    .sclk(sclk)
  );
  (* src = "spi_system.v:101" *)
  \$paramod\spi_slave\mode=0  slave3 (
    .cs_n(cs_n[3]),
    .miso(miso3),
    .mosi(mosi),
    .rst(rst),
    .sclk(sclk)
  );
endmodule
